#  .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Update activity log
        uses: greatfish01/activity-log@t5
        with:
          GITHUB_USERNAME: "greatfish01"
          GITHUB_TOKEN: ${{ secrets.RAHASIA_NEGARA }}

